server:
  port: 9000

logging:
  level:
    root: INFO
    com.showka.multitenant_sample: INFO
    org.hibernate.SQL: INFO

spring:
  profiles:
    include:
      - development
      - local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20 # batch (bulk) insert size
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./database/mts;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://mts-dev-01.jp.auth0.com/

auth0:
  audience: https://api.mts-dev-01/
  domain: mts-dev-01.jp.auth0.com
  client-id: V0gH6JrlRhTHbob4wuXOkYpY2nZcR0TP

mts:
  file:
    root: ${user.dir}/data
  search:
    limit: 1000
